### ISSUE TITLE
createBuffer from the example online doesn't exist.

### ISSUE THREAD

**Issue by seanparsons** [phaazon/luminance#1]
Pretty much as the title says, looking at this page:
http://phaazon.blogspot.fr/2015/07/introducing-luminance-safer-opengl-api.html

GHC tells me that createBuffer isn't in scope and I can't find it in the project.

**Comment by phaazon** [comment]
Indeed. For now, you have three functions to do that: `writeBuffer`, `readBuffer` and `readWriteBuffer`. The `createBuffer` is an hypothetical function that would use a typeclass to deduce which version of the three ones to call.

**Comment by phaazon** [comment]
Yeah, nevermind. I’ll add that `createBuffer` function and remove the three others. Should be up in a few minutes.

**Comment by seanparsons** [comment]
Oh nice, cheers!
