### ISSUE TITLE
Master appears to be broken because of Graphics.Luminance.VertexArray.

### ISSUE THREAD

**Issue by seanparsons** [phaazon/luminance#2]
Setup.hs: can't find source for Graphics/Luminance/VertexArray in src,

**Comment by phaazon** [comment]
Fixed.

**Comment by seanparsons** [comment]
Thank you very much, hopefully I'll be able to help in some way with this library as it looks like exactly what I wanted!

**Comment by phaazon** [comment]
:) Well, yeah. I think it’s the right direction!
