### ISSUE TITLE
References to GLFW-b cause broken links.

### ISSUE THREAD

**Issue by Chobbes** [phaazon/luminance#44]
Graphics/Luminance.hs has several points where it references "GLFW-b" in double quotes, which haddock attempts to treat as a link to a GLFW-b module within luminance. Since no such module exists this leads to several broken links in the documentation.

I would create a pull request right now, but I'm not sure what the best option is:

- Escape the double quotes
- Remove the double quotes
- Provide a link to the hackage page for GLFW-b
- Provide a link to the stackage page for GLFW-b

What do you think would be best? I think a link to the hackage page might be the best option. Some people might not be aware of what GLFW-b is, so the references might be confusing without the context. My reason for voting for the hackage page is based on my assumption (with no evidence) that most people look up documentation on hackage as opposed to stackage. Ideally we would keep people on the site they started with, but as far as I am aware there isn't a way to do this with haddock.

https://www.haskell.org/haddock/doc/html/ch03s08.html#idm140354810751008

**Comment by phaazon** [comment]
Yep, a link to hackage would be the best option. I used double quotes to create such a link but I didn’t know it’s required to build against that module to have its documentation (and it’s actually pretty logical with hindsight).
