### ISSUE TITLE
Vertex attributes

### ISSUE THREAD

**Issue by elaye** [phaazon/luminance#48]
Hello,
First of all, thanks a lot for this library, this is awesome!
This is more a question about how to use the library than an issue.
I managed to make a mesh, render it, and everything works fine.
What I'd like to do now is add normals to my mesh. I understand that I need to use `VertexAttribute` but I have no idea how to proceed. Let's say that my mesh is represented like this:
```
data Mesh = Mesh
  { positions :: [V3 Float]
  , normals :: [V3 Float]
  }
```
What do I need to do to make it an array of vertices with attributes?

**Comment by phaazon** [comment]
Hi,

You need to interleave your vertices’ data. You can use the `(:.)` type to make it simpler. In your case, you need a function `Mesh -> [V3 Float :. V3 Float]`.
