### ISSUE TITLE
Setting the clear colour

### ISSUE THREAD

**Issue by SwiftsNamesake** [phaazon/luminance#49]
I can't find any references to glClearColor in the entire codebase. Is this a conscious omission?

Is there any way of setting the clear colour (other than using a quad that fills up the entire screen)?

**Comment by phaazon** [comment]
Yeah, it’s automatically set to pure dark, you cannot change it, I’m sorry… I’ve migrated the project in Rust (in which you can set the clear colour). I recommend you not use luminance and have a look to still maintained Haskell graphics frameworks (gpipe, lambdacube, etc.).

**Comment by SwiftsNamesake** [comment]
Sorry to hear it, I really liked the idea of a type-safe OpenGL wrapper.

Are you saying you've abandoned the Haskell version in favour of Rust?

**Comment by phaazon** [comment]
Yes, that’s the idea. However, you might find other safe OpenGL wrappers – have a look to `opengl` on hackage, even though the aims are not the same as luminance’s.
